//! Shell hook file + marked stubs in zshrc/bashrc.

use std::path::{Path, PathBuf};

use crate::error::{Error, Result};

pub const HOOK_BEGIN: &str = "# >>> machine_setup schedule hook >>>";
pub const HOOK_END: &str = "# <<< machine_setup schedule hook <<<";

pub fn hook_script_path(temp_dir: &Path) -> PathBuf {
    temp_dir.join("schedule_hook.sh")
}

/// Write the sourced hook script that calls `schedule notify`.
pub fn write_hook_script(temp_dir: &Path, binary: &Path) -> Result<PathBuf> {
    std::fs::create_dir_all(temp_dir)?;
    let path = hook_script_path(temp_dir);
    let bin = binary.display();
    let body = format!(
        r#"# Generated by machine_setup schedule apply — do not edit by hand.
# shellcheck shell=sh
if command -v "{bin}" >/dev/null 2>&1 || [ -x "{bin}" ]; then
  "{bin}" schedule notify 2>/dev/null || true
fi
"#
    );
    std::fs::write(&path, body)?;
    Ok(path)
}

fn stub_block(hook_path: &Path) -> String {
    format!(
        "{HOOK_BEGIN}\n[ -f \"{p}\" ] && . \"{p}\"\n{HOOK_END}\n",
        p = hook_path.display()
    )
}

/// Insert or refresh the marked stub in a shell rc file.
pub fn install_stub(rc_path: &Path, hook_path: &Path) -> Result<bool> {
    let block = stub_block(hook_path);
    if rc_path.exists() {
        let content = std::fs::read_to_string(rc_path)?;
        if let Some(updated) = replace_marked_block(&content, &block) {
            std::fs::write(rc_path, updated)?;
            return Ok(true);
        }
        let mut new_content = content;
        if !new_content.ends_with('\n') {
            new_content.push('\n');
        }
        new_content.push_str(&block);
        std::fs::write(rc_path, new_content)?;
        Ok(true)
    } else if let Some(parent) = rc_path.parent() {
        std::fs::create_dir_all(parent)?;
        std::fs::write(rc_path, block)?;
        Ok(true)
    } else {
        Err(Error::ScheduleError(format!(
            "cannot install hook stub at {}",
            rc_path.display()
        )))
    }
}

/// Remove the marked stub from an rc file. Returns true if something was removed.
pub fn remove_stub(rc_path: &Path) -> Result<bool> {
    if !rc_path.exists() {
        return Ok(false);
    }
    let content = std::fs::read_to_string(rc_path)?;
    match strip_marked_block(&content) {
        Some(updated) => {
            std::fs::write(rc_path, updated)?;
            Ok(true)
        }
        None => Ok(false),
    }
}

fn replace_marked_block(content: &str, new_block: &str) -> Option<String> {
    let start = content.find(HOOK_BEGIN)?;
    let end_rel = content[start..].find(HOOK_END)?;
    let end = start + end_rel + HOOK_END.len();
    let mut end = end;
    if content[end..].starts_with('\n') {
        end += 1;
    }
    let mut out = String::new();
    out.push_str(&content[..start]);
    out.push_str(new_block);
    out.push_str(&content[end..]);
    Some(out)
}

fn strip_marked_block(content: &str) -> Option<String> {
    let start = content.find(HOOK_BEGIN)?;
    let end_rel = content[start..].find(HOOK_END)?;
    let mut end = start + end_rel + HOOK_END.len();
    if content[end..].starts_with('\n') {
        end += 1;
    }
    let mut out = String::new();
    out.push_str(&content[..start]);
    out.push_str(&content[end..]);
    Some(out)
}

/// Default rc paths under `home` for zsh and bash.
pub fn default_rc_paths(home: &Path) -> Vec<PathBuf> {
    vec![home.join(".zshrc"), home.join(".bashrc")]
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn stub_insert_refresh_remove() {
        let dir = tempdir().unwrap();
        let rc = dir.path().join(".zshrc");
        std::fs::write(&rc, "# existing\n").unwrap();
        let hook = dir.path().join("schedule_hook.sh");
        std::fs::write(&hook, "echo hi\n").unwrap();

        assert!(install_stub(&rc, &hook).unwrap());
        let c1 = std::fs::read_to_string(&rc).unwrap();
        assert!(c1.contains(HOOK_BEGIN));
        assert!(c1.contains("schedule_hook.sh"));

        let hook2 = dir.path().join("other_hook.sh");
        assert!(install_stub(&rc, &hook2).unwrap());
        let c2 = std::fs::read_to_string(&rc).unwrap();
        assert_eq!(c2.matches(HOOK_BEGIN).count(), 1);
        assert!(c2.contains("other_hook.sh"));

        assert!(remove_stub(&rc).unwrap());
        let c3 = std::fs::read_to_string(&rc).unwrap();
        assert!(!c3.contains(HOOK_BEGIN));
        assert!(c3.contains("# existing"));
    }
}
